name: CI/CD
run-name: ${{ inputs.description || 'CI/CD' }}

on:
  pull_request:
  push:
    branches: [
      test-ci-cd,
    ]
  workflow_dispatch:
    inputs:
      description:
        required: true
        type: string
        description: Short job run description
